### ISSUE TITLE
Краш при запуске

### ISSUE THREAD

**Issue by SecretAgent12** [MJaroslav/Reflectors#1]
[11:44:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[11:44:46] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[11:44:47] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
Exception in thread "main" [11:44:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.ExceptionInInitializerError
[11:44:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.github.mjaroslav.reflectors.v3.Reflectors$FMLLoadingPluginAdapter.injectData(Reflectors.java:400)
[11:44:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:119)
[11:44:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[11:44:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[11:44:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
[11:44:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at GradleStartServer.main(Unknown Source)
[11:44:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: java.lang.IllegalArgumentException: value already present: func_130071_aq
[11:44:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.collect.HashBiMap.put(HashBiMap.java:238)
[11:44:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.collect.HashBiMap.put(HashBiMap.java:215)
[11:44:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.github.mjaroslav.reflectors.v3.Reflectors.loadMappings(Reflectors.java:340)
[11:44:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.github.mjaroslav.reflectors.v3.Reflectors.<clinit>(Reflectors.java:419)
[11:44:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	... 6 more

Process finished with exit code 1

**Comment by SecretAgent12** [comment]
версия v4 так-же краш

**Comment by MJaroslav** [comment]
Скорее всего не актуально, но что и как ты пытался запатчить?
